-dev@updatability(Bonfire): `--rebuild` does not work when building the first time
Hence the `bonfire.${flavour}.update.package` will only be rebuilt
when Bonfire's version has been updated.

> error: some outputs of '/nix/store/fjfaqq0997m0rlqr34r2wqnqwy0is6gb-bonfire-ember-update-1.0.3-alpha.10.drv' are not valid, so checking is not possible